<?php
namespace controllers;
use Ubiquity\attributes\items\router\Route;

 /**
 * Controller TodosController
 **/
class TodosController extends ControllerBase{

    const CACHE_KEY = 'datas/lists/';
    const EMPTY_LIST_ID='not saved';
    const LIST_SESSION_KEY='list';
    const ACTIVE_LIST_SESSION_KEY='active-list';


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->menu();
    }

    #[Route(path: "_default",name: "home")]
	public function index(){
        $this->displayList();

        if(USession::exist(self::LIST_SESSION_KEY)) {
            $list = USession::get(self::LIST_SESSION_KEY);
            return $this->displayList();
        }

        $this.showMessage('Bienvenue !','TodoLists permet de gérer des listes ...','info','info');
    }


	#[Get(path: "todos/delete/{index}",name: "todo.delete")]
	public function deleteElement($index){
		
	}

	#[Post(path: "todos/edit/{index}",name: "todo.edit")]
	public function editElement($index){
		
	}

	#[Post(path: "todos/add/", name: "todo.add")]
	public function addElement(){
		
	}

	#[Get(path: "todos/loadList/{uniquid}",name: "todo.loadList")]
	public function loadList($uniquid){
		
	}

	#[Post(path: "todos/loadList/",name: "todo.loadListPost")]
	public function loadListFromForm(){
		
	}

	#[Get(path: "todos/new/{force}",name: "todo.new")]
	public function newlist($force=false){
		
	}

	#[Get(path: "todos/saveList/",name: "todo.save")]
	public function saveList(){
		
	}


	private function menu() {
        $this->loadView('TodosController/index.html');
    }

    private function displayList() {
        $this->loadView('TodosController/displayList.html',['list'->$list]);
    }


    private function showMessage(string $header, string $message, string $type='info', string $icon='info circle', array $buttons=[]) {
        $this.loadView('TodosController/showMessage.html'.
            compact());
    }
}
