<?php
namespace controllers;
use Ubiquity\attributes\items\router\Route;
use Ubiquity\controllers\Router;
use Ubiquity\utils\http\URequest;
use Ubiquity\utils\http\USession;

/**
 * Controller TodosController
 **/
class TodosController extends ControllerBase{
    const CACHE_KEY = 'datas/lists/';
    const EMPTY_LIST_ID='not saved';
    const LIST_SESSION_KEY='list';
    const ACTIVE_LIST_SESSION_KEY='active-list';

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->menu();
    }

    #[Route(path: "_default",name: "home")]
	public function index(){
        if(USession::exist(self::LIST_SESSION_KEY)) {
            $list = USession::get(self::LIST_SESSION_KEY);
            return $this->displayList($list);
        }

        $this->showMessage('Bienvenue !','TodoLists permet de gérer des listes...','info','info circle',
        [['url'=> Router::path('todos.new'),'caption'=>'Créer une nouvelle liste','style'=>'basic inverted']]);
    }


	#[Get(path: "todos/delete/{index}",name: "todos.delete")]
	public function deleteElement($index){
		
	}

	#[Post(path: "todos/edit/{index}",name: "todos.edit")]
	public function editElement($index){
		
	}

	#[Post(path: "todos/add/", name: "todos.add")]
	public function addElement(){
		/*$list=USession::get(self::LIST_SESSION_KEY);
		$list[]=URequest::post('element');
		USession::set(self::LIST_SESSION_KEY,$list);
		$this->displayList($list);*/

        $list=USession::get(self::LIST_SESSION_KEY);
        if(URequest::has('elements')) {
            $elements=explode("\n",URequest::post('elements'));
            foreach($elements as $elm) {
                $list[]=$elm;
            }
        } else {
            $list[]= URequest::post('element');
        }
        USession::set(self::LIST_SESSION_KEY,$list);
        $this->displayList($list);
	}

	#[Get(path: "todos/loadList/{uniquid}",name: "todos.loadList")]
	public function loadList($uniquid){
		
	}

	#[Post(path: "todos/loadList/",name: "todos.loadListPost")]
	public function loadListFromForm(){
		
	}

	#[Get(path: "todos/new/{force}",name: "todos.new")]
	public function newlist($force=false){
		
	}

	#[Get(path: "todos/saveList/",name: "todos.save")]
	public function saveList(){
		
	}


	private function menu() {
        $this->loadView('TodosControllerView/index.html');
    }

    private function displayList(array $list) {
        $this->loadView('TodosControllerView/displayList.html',['list'=>$list]);
    }

    private function showMessage(string $header, string $message, string $type='info', string $icon='info circle', array $buttons=[]) {
        $this->loadView('TodosControllerView/showMessage.html'.
            compact('header', 'type', 'icon', 'message','buttons'));
    }
}
